# 异常

## 什么是异常

- 概念：程序在运行过程中出现的特殊情况

- 处理的必要性：任何程序都可能存在大量的未知问题、错误；如果不对这些问题进行正确处理，则可能导致程序的中断，造成不必要的损失。

## 异常的分类

- `Throwable`类：可抛出的，一切错误或异常的父类，位于java.lang包中

  - `Error`类：JVM、硬件、执行逻辑错误，不能手动处理
  - `Exception`类：程序在运行和配置中产生的问题，可处理
    * `RuntimeException`：运行时异常，可处理，可不出来
    * CheckedException（除了RuntimeException的所有）：必须处理

```java
public class TestException {
    
    
    public static void m1() {
        // java.lang.NullPointerException
        Object o = null;
        o.hashCode();

        // java.lang.ArrayIndexOutOfBoundsException
        int[] nums = new int[4];
        int a = nums[5];

        // java.lang.StringIndexOutOfBoundsException
        String str = "abc";
        char c = str.charAt(4);
    }

    
}
```

## 异常的产生
- 自动抛出异常：当程序在运行时遇到不符合规范的代码或结果时，会产生异常

- 手动抛出异常：
  - 语法：`throw new 异常类型("实际参数")`

- 产生异常结果：相当于遇到`return`语句，导致程序因异常而终止

# 异常的声明和处理

## 异常的传递
- 按照方法的调用链反向传递，如始终没有处理异常，最终会由JVM进行默认异常处理（打印堆栈跟踪信息）-- RuntimeException

- 受查异常（CheckedException）：`throws 声明异常`，修饰在方法参数列表后端

```java

public static void m1() throws Exception { // 若不进行处理，会交由JVM处理
    m2();
}

public static void m2() throws Exception {
    m3();
}


public static void m3() throws Exception { // 消极处理（告知可能产生的异常）
    
    //

    throw new Exception();

}
```

- 运行时异常（RuntimeException）

## 异常的处理

```java
Scanner input = new Scanner(System.in);

try {
    int num1 = input.nextInt();
    int num2 = input.nextInt();
    System.out.println(num1 / num2 );// 可能出现异常的代码
} catch(ArithmeticException e) { // new ArithmeticException();
    // 异常的处理

    // 方案1，自定义处理
    System.out.println("注意，除数不能为0!"); 

    // 方案2，打印堆栈跟踪信息
    //e.printStackTrace();

    // 方案3，单独获取getMessage作为异常原因
    //e.getMessage();
} catch(InputMismatchException e){ // 输入不匹配异常
    System.out.println("请输入有效整数!")
} catch(RuntimeException e) {
    System.out.println("未知运行时异常!"); 
} catch(Exception e) { // 最大类型的异常，注意要写在最后，会依次进行查询异常处理
    System.out.println("未知受查异常!"); 
} finally {
    // 无论是否出现异常，都需执行的代码，常用于释放资源
}
```
> 注：多重catch，遵循从子（小）到父（大）的顺序，父类异常在最后

## 自定义异常
- 需继承自`Exception`或`Exception`子类，常用`RuntimeException`

- 必要提供的构造方法
  - 无参数构造方法
  - `String message`参数的构造方法

```java
class Test {

    public static void main(String[] args) {

        Student st = new Student();

        try { // 必须处理，否则编译不通过
            s.setAge(11);
        } catch(AgeException e) {
            e.printStackTrace();
        }

        s.setSex("aa"); // 可以不处理，默认虚拟机处理打印堆栈信息
    }
}

// 受查异常
class AgeException extends Exception {

    public AgeException() {
        super();
    }

    public AgeException(String message) {
        super(message);
    }
}

// 运行时异常
class SexMismatchException extends RuntimeException {

}

class Student {

    private int age;
    private String sex;

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) throws AgeException{
        if (age > 0 && age < 253) {
            this.age = age;
        } else {
            // 异常
            throw new AgeException("输入正确的年龄区间：[1,253]");
        }
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        if (sex.equals("男") || sex.equals("女")) {
            this.sex = sex;
        } else {
            // 异常
            throw new SexMismatchException();
        }
    }
}
```

## 带有异常声明的方法覆盖
- 方法名、参数列表、返回值类型必须和父类相同

- 子类的访问修饰符和父类相同或是比父类更宽泛

- **子类中的方法，不能抛出比父类更多、更宽的异常**